name: Testing
on:
- push
permissions:
  contents: read
  deployments: write
jobs:
  test:
    name: Cypress Testing
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup node.js
      uses: actions/setup-node@v4
      with:
        node-version: lts/*
        check-latest: true
    - name: Get yarn cache directory
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      with:
        path: "${{ steps.yarn-cache-dir-path.outputs.dir }}"
        key: "${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}"
        restore-keys: "${{ runner.os }}-yarn-\n"
    - name: Install dependencies
      id: install-dependencies
      run: npm i
    - name: Building
      id: build
      run: npm run build
    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        start: npm run dev
        wait-on: "http://localhost:3000"
        wait-on-timeout: 120
        browser: chrome
      env:
        GREETING: ${{ secrets.GREETING }}
